PRAGMA foreign_keys = ON;

CREATE TABLE USERS (
    USER_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT,
    EMAIL TEXT,
    PASSWORD TEXT,
    GENDER TEXT,
    PHONE_NUMBER INTEGER,
    DOB DATE,
    ROLE TEXT
);

CREATE TABLE DEPARTMENT (
    DEPT_ID TEXT PRIMARY KEY,
    DEPT_NAME TEXT
);

CREATE TABLE DOCTORS (
    DOC_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER,
    DEPT_ID TEXT,
    NAME TEXT,
    SPECIALIZATION TEXT,
    FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID),
    FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT (DEPT_ID)
);


INSERT INTO USERS(NAME,EMAIL,PASSWORD,GENDER,PHONE_NUMBER,DOB,ROLE)
VALUES('ADMIN','admin@123','admin123','M','9962286705','2005-06-20','ADMIN');

INSERT INTO DEPARTMENT(DEPT_ID,DEPT_NAME)
VALUES('HMGM','GENERAL MEDICINE');

INSERT INTO DEPARTMENT(DEPT_ID,DEPT_NAME)
VALUES('HMS','SURGERY');

INSERT INTO DEPARTMENT(DEPT_ID,DEPT_NAME)
VALUES('HMP','PEDIATRICS');

INSERT INTO DEPARTMENT(DEPT_ID,DEPT_NAME)
VALUES('HMC','CARDIOLOGY');

INSERT INTO DEPARTMENT(DEPT_ID,DEPT_NAME)
VALUES('HMO','ORTHO');

INSERT INTO DEPARTMENT(DEPT_ID,DEPT_NAME)
VALUES('HMGY','GYNECOLOGY');


CREATE TABLE PATIENTS(
    PATIENT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER,
    PATIENT_NAME TEXT,
    ADDRESS TEXT,
    CONTACT TEXT,
    BLOOD_GRP TEXT,
    ALLERGIES TEXT,
    FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID)
);

CREATE TABLE APPOINTMENTS(
    APPOINTMENT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PATIENT_ID INTEGER,
    PATIENT_NAME TEXT,
    DOC_ID INTEGER,
    DOC_NAME TEXT,
    APPOINTMENT_DATE DATE,
    APPOINTMENT_TIME TIME,
    STATUS TEXT,
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS (PATIENT_ID),
    FOREIGN KEY (DOC_ID) REFERENCES DOCTORS (DOC_ID)
);

INSERT INTO PATIENTS (USER_ID_ID,PATIENT_NAME,ADDRESS,CONTACT,BLOOD_GRP,ALLERGIES) VALUES (2,'Narendran','Chennai',9962286700,'B+','No');
INSERT INTO APPOINTMENTS (PATIENT_ID,PATIENT_NAME,DOC_ID,DOC_NAME,APPOINTMENT_DATE,APPOINTMENT_TIME,STATUS) VALUES (2,'Narendran',1,'Dr. Bharath','2025-11-10','08:30:00','Booked');


INSERT INTO USERS(NAME,EMAIL,PASSWORD,GENDER,PHONE_NUMBER,DOB,ROLE)
VALUES('Sridhar','sridhar@gamil.com','sridhar','M','9852147630','2006-01-16','Patient');

INSERT INTO USERS(NAME,EMAIL,PASSWORD,GENDER,PHONE_NUMBER,DOB,ROLE)
VALUES('Harshad','harshad@gmail.com','harshad','M','9632587410','2005-08-04','Patient');

INSERT INTO USERS(NAME,EMAIL,PASSWORD,GENDER,PHONE_NUMBER,DOB,ROLE)
VALUES('Harish','harish@gmail.com','harish','M','9856321470','2005-09-22','Patient');

INSERT INTO USERS(NAME,EMAIL,PASSWORD,GENDER,PHONE_NUMBER,DOB,ROLE)
VALUES('Surya','surya@gmail.com','surya','M','9514736820','2006-06-20','Patient');

INSERT INTO USERS(NAME,EMAIL,PASSWORD,GENDER,PHONE_NUMBER,DOB,ROLE)
VALUES('Bharath','bharath@gmail.com','bharath','M','9514730820','2001-06-07','Doctor');

DROP TABLE PATIENTS;

INSERT INTO PATIENTS (USER_ID,PATIENT_NAME,ADDRESS,CONTACT,BLOOD_GRP,ALLERGIES) VALUES (2,'Narendran','Chennai',9962286700,'B+','No');
INSERT INTO PATIENTS (USER_ID,PATIENT_NAME,ADDRESS,CONTACT,BLOOD_GRP,ALLERGIES) VALUES (3,'Sridhar','Coimbatore',9852147630,'AB+','No');
INSERT INTO PATIENTS (USER_ID,PATIENT_NAME,ADDRESS,CONTACT,BLOOD_GRP,ALLERGIES) VALUES (4,'Harshad','Chennai',9632587410,'B+','No');
INSERT INTO PATIENTS (USER_ID,PATIENT_NAME,ADDRESS,CONTACT,BLOOD_GRP,ALLERGIES) VALUES (5,'Harish','Hosur',9856321470,'O+','No');
INSERT INTO PATIENTS (USER_ID,PATIENT_NAME,ADDRESS,CONTACT,BLOOD_GRP,ALLERGIES) VALUES (6,'Surya','Chennai',9514736820,'A+','No');

INSERT INTO APPOINTMENTS (PATIENT_ID,PATIENT_NAME,DOC_ID,DOC_NAME,APPOINTMENT_DATE,APPOINTMENT_TIME,STATUS)
VALUES (1,'Narendran',1,'Dr. Bharath','2025-11-10','08:30:00','Booked');
INSERT INTO APPOINTMENTS (PATIENT_ID,PATIENT_NAME,DOC_ID,DOC_NAME,APPOINTMENT_DATE,APPOINTMENT_TIME,STATUS)
VALUES (2,'Sridhar',1,'Dr. Bharath','2025-11-10','09:30:00','Booked');
INSERT INTO APPOINTMENTS (PATIENT_ID,PATIENT_NAME,DOC_ID,DOC_NAME,APPOINTMENT_DATE,APPOINTMENT_TIME,STATUS)
VALUES (3,'Harshad',1,'Dr. Bharath','2025-11-10','10:30:00','Booked');
INSERT INTO APPOINTMENTS (PATIENT_ID,PATIENT_NAME,DOC_ID,DOC_NAME,APPOINTMENT_DATE,APPOINTMENT_TIME,STATUS)
VALUES (4,'Harish',1,'Dr. Bharath','2025-11-10','11:30:00','Booked');
INSERT INTO APPOINTMENTS (PATIENT_ID,PATIENT_NAME,DOC_ID,DOC_NAME,APPOINTMENT_DATE,APPOINTMENT_TIME,STATUS)
VALUES (5,'Surya',1,'Dr. Bharath','2025-11-10','12:30:00','Booked');