CREATE TABLE USERS (
    USER_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT,
    EMAIL TEXT,
    PASSWORD TEXT,
    GENDER TEXT,
    PHONE_NUMBER INTEGER,
    DOB DATE,
    ROLE TEXT
);


INSERT INTO USERS(NAME,EMAIL,PASSWORD,GENDER,PHONE_NUMBER,DOB,ROLE)
VALUES('ADMIN','admin@123','admin123','M','9962286705','2005-06-20','ADMIN');

